{% set version = "1.7.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ore/ore_{{ version }}.tar.gz
  sha256: 851323539656baca962a003b724669524145e8fab813bab42594f41060c94567

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('ore')"           # [not win]
    - "\"%R%\" -e \"library('ore')\""  # [win]

about:
  home: https://github.com/jonclayden/ore
  license: BSD_3_clause
  summary: Provides an alternative to R's built-in functionality for handling regular expressions, based on the Onigmo library. Offers first-class compiled regex objects, partial matching and function-based substitutions, amongst other features.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENCE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ore
# Version: 1.6.3
# Date: 2019-10-31
# Title: An R Interface to the Onigmo Regular Expression Library
# Author: Jon Clayden, based on Onigmo by K. Kosako and K. Takata
# Maintainer: Jon Clayden <code@clayden.org>
# Suggests: crayon, rex, testthat
# Description: Provides an alternative to R's built-in functionality for handling regular expressions, based on the Onigmo library. Offers first-class compiled regex objects, partial matching and function-based substitutions, amongst other features.
# Encoding: UTF-8
# Biarch: true
# License: BSD_3_clause + file LICENCE
# Collate: workspace.R file.R dict.R ore.R match.R es.R zzz.R
# URL: https://github.com/jonclayden/ore
# BugReports: https://github.com/jonclayden/ore/issues
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2019-11-02 17:24:24 UTC; jon
# Repository: CRAN
# Date/Publication: 2019-11-02 18:50:02 UTC
