# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UXc92dT/BJE8ObnVBvGGgtj9YOXNr0N3BeNl95UotIF3gzTaC/fmcb/9K2Hf1JpQX39ALmuMusXKxCY788l5pzjTJj5h6YYnxzhAOhSX9AAb6OIbLibV4fZSI4iTbRXOvTXJloTCIKujzeh4YEU1eo14pYLOtS2tg9XVfp5nnmiGkWtHfkdglBjYiyALMZTdfyK71GD/Gr46zKbrlA2hoTewZQkuJdy2rUw4Ij1wHJt4smMRi9BeD3yHXEQp2aNPTRlQsxgYV55Bw8blP+kBBqjCZoyzHAIzdefmR1H21LfkYNrem268PTVhPnFXQsrVwfeluN8rzLj4k8iCkZWoeKn+ZubVv9lvPmuKlhyLQDVf+ZwJxhyHCU49Og/DN8NWzP3Q4at9b6h/0JFbfb9UoepB8DkE8OVmIDmGHvB6VGgmQmxq5XpjhfHC+BP3T3Qg94y0xeAhmkDtEpJXOLLB8mRGCCn2oNJQigpgHNx4yjjxrIhV8rlxrEY090vSiefUPC/Tf3U7C0Al9TpliiwAsnNsjMTQa8fwkCCsgsNkgDJgVkq+l6ZKhJZUUXEqrRtVVnTKs2fZMauaIz82r4AWaydrjfBok2vBEL6lxL2t9IiGEMdkpEeseWG4s8lLG3MnrcjHd39m+hW+1/VDA2aKzZBysSUo+veGiewh74w4I4s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
