travis:
  secure:
    BINSTAR_TOKEN: UXc92dT/BJE8ObnVBvGGgtj9YOXNr0N3BeNl95UotIF3gzTaC/fmcb/9K2Hf1JpQX39ALmuMusXKxCY788l5pzjTJj5h6YYnxzhAOhSX9AAb6OIbLibV4fZSI4iTbRXOvTXJloTCIKujzeh4YEU1eo14pYLOtS2tg9XVfp5nnmiGkWtHfkdglBjYiyALMZTdfyK71GD/Gr46zKbrlA2hoTewZQkuJdy2rUw4Ij1wHJt4smMRi9BeD3yHXEQp2aNPTRlQsxgYV55Bw8blP+kBBqjCZoyzHAIzdefmR1H21LfkYNrem268PTVhPnFXQsrVwfeluN8rzLj4k8iCkZWoeKn+ZubVv9lvPmuKlhyLQDVf+ZwJxhyHCU49Og/DN8NWzP3Q4at9b6h/0JFbfb9UoepB8DkE8OVmIDmGHvB6VGgmQmxq5XpjhfHC+BP3T3Qg94y0xeAhmkDtEpJXOLLB8mRGCCn2oNJQigpgHNx4yjjxrIhV8rlxrEY090vSiefUPC/Tf3U7C0Al9TpliiwAsnNsjMTQa8fwkCCsgsNkgDJgVkq+l6ZKhJZUUXEqrRtVVnTKs2fZMauaIz82r4AWaydrjfBok2vBEL6lxL2t9IiGEMdkpEeseWG4s8lLG3MnrcjHd39m+hW+1/VDA2aKzZBysSUo+veGiewh74w4I4s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
