travis:
  secure:
    BINSTAR_TOKEN: QRBuBOIcRuA/dTk9VlQ986wnbgRFD+4Kv8eQp4eS93ZIZ/2saOsb50DPJ5+GpXL3F02YLhdttZfy3lPZR7fdPn6HQHdXDgkLIdWv8P1+i4Sba21YQaEqluwrUJ3QQ01MguN8dlnqI6ZF6qSsFjhiPjVpMBPKg6lYjlGvAXS1SCUYQveuwY2gqCr/NlOEhloyUND8Fhm6hJIGraPBFUv3ivKoeFYSQI2j4b6alif6bmz0GC54PlRgmqc7RvT5yQP41w2dWso9kiiNsZ3jn5i6bcPsapFYDCwQ3XmTxBhYABxjn2iLaLeGNBX/Uif3KvsMXR6acrf+yH6tiOUOjNvSGgZtmy3GJ4tlZEuZynU0qfFdcDJ0TjYbDQi490lI8mrt4HOoZJH0/FR8KYCNrqMGcDpckj5GeJm0n+BW79ZmZ7+McMKqiQVb3ctbqu8VkvgwoTgAKSD+tijQfw/UMeSUwve/0wy/JbuypEFPluMeWVcCv1raeTpgFd+Difnsf80Pc5bTo90sLsr63nchXzoSwdlITh85JmO/wNCww6nv3E21hLCGpXFTZkCdDLxCZuw8qVgdldxqzwX+qhwJUi6jQaGmkEvS+CEx7d1zKjWXz5RpoFTIIHfLIfwVL5X19a97T8a5TnNwZy9LdJo3Bi6ie/L1kMkjh4m/v8PhIYE5LWM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
