travis:
  secure:
    BINSTAR_TOKEN: LmunqI4VnjxOuNtkXoEPAZ2Vvk5eFRWCGxVEtaAgUU51SHhzKztPbZLzWyO6/YVFJ7TyFRp2Ne/q+qMHHcz+iK/Ni8Aby04UFyk4rXg3W+GJ6R7CqpBTUf2lk8zIknnjXo0TVleq5iAhHqaavSvEF2ZQuoQgHeNNJY1UTC2ZuFDzbjnBTB8Pd3FjGQRh6VxuixF4dJISfqFwnZlcJxCtU5TshEItViyCYD3NGthhU4CQqC5ESmPGX4YBFtYdSrX37E2rQEQhkOfAGUWr3oHIkrWMK/BDTkOUHVz+6CM4jL5HV7iZwA75AXNt4K837beyNytEh4jzVj9GP4scj9CTJOPuHk253y3FLK4Ov/8du/eDXqjgU9XNqEGAw7gn1zC8WKI1uPMHHuzlgRc3CBNO5vn/5cQvyDw5sXJnQARcuwniMoVpVI02RoYip+M3jVA132ChoeppAR5kFajzSj+j9QQ8BwbrNrWen+ADyInrioK+ANXcawSHYhxd0bYtCq5I+bHRonVIlh9K6RbwC5JXROCpTrR8uCcvFT+ZyCB9+QvWx5yjDIZKws66SktLFyvHM3WDrj7jO2JaiXNfsEdTR+OCznugZXZ1sdC4slnCE3Kq0gbVJ1T0eRzZhCEXD8VHB50OvZjwqdwvc3J40/VcnBkdrliAKLjD8jqMklfyb6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
