travis:
  secure:
    BINSTAR_TOKEN: tiQNHGQqlCI3gLaY6MQ21tQQYkkgK92EmCFHI/jd1a5b+FkyzzE3yjBXhC3oxj+463VSBeauqthBKbHnkpW31wR64IW2qBIo2w4rpy2c+YDMhSx5d/oKCdUuQqESY8yjIqsLfUPECRoDmhoTsE0IOi9y2tLiA0MbG5NxifxucWe19MumKNpL2zPrzAzS/KKL1J0ezP71t7Ut1wVEUpWZhx8nvYKEpVlCwD27nRO4z7G4JHAXLPHXOe7lqkJ6VOd/OBB25pZVW+5PEvVOCZcSDzBJq5IpAAm2psVXfZqRqrQ1VGgYgF/KLb5jNooKHaeA0cgCI+BgvPPLnrFOBYRK92ROurXq/tGRp8x4Sug9OvvMu8fYMr/09X+vEhxZbicKVcxWmkHFsrKAJaiWhgF8R/rVV26ho/7aKyQJd7J0JHDZV5aCYqHDsb1wFRKXdxj4L6Uj+Skg8JpDiND1xPI1J83zoEPazXLtC24JkZ+h8Cq9g8BOGRG7/pk6DmSnOPBrufNCBebcyFekgE2ftUbDVIbB4jzvPw7x5CFIR2bx2vX5d7Adj85x+yevet6KAAQaYlwVg2d+6++7EGIHFFvHs5/bVv9gccCzPjiIP3WnBM7Q+YwSUnwUGVOaC+GDR/s0Ay6HueqJmfSaey/0iD3yoCayioGP95GVmvsC8m0cruU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
